services:
  consul-server:
    image: docker.io/bitnami/consul:1.19.0
    volumes:
      - consul-server:/bitnami/consul

  consul-client:
    # Клиент не обязательно нужен, можно использовать consul сервер в качестве клиента.
    # Тут используется клиент чтобы можно было скопировать пример, если потребуется другая конфигурация.
    image: docker.io/bitnami/consul:1.19.0
    depends_on:
      - consul-server
    environment:
      - CONSUL_AGENT_MODE=client
      - CONSUL_BOOTSTRAP_EXPECT=0
      - CONSUL_RETRY_JOIN_ADDRESS=consul-server
    ports:
      - "8500:8500"
    volumes:
      - consul-client:/bitnami/consul

  nomad-server:
    build: nomad
    depends_on:
      - consul-client
    volumes:
      - ./nomad-server/config:/etc/nomad.d:ro
      # После команды `docker compose down` нужно пересоздать volume
      # с помощью команды `docker volume rm infra_nomad-server`
      - nomad-server:/opt/nomad

volumes:
  consul-server:
    driver: local
  consul-client:
    driver: local
  nomad-server:
    driver: local
