services:
  consul-server:
    image: docker.io/bitnami/consul:1.19.0
    volumes:
      - consul-server:/bitnami/consul

  consul-client:
    image: docker.io/bitnami/consul:1.19.0
    depends_on:
      - consul-server
    environment:
      - CONSUL_AGENT_MODE=client
      - CONSUL_BOOTSTRAP_EXPECT=0
      - CONSUL_RETRY_JOIN_ADDRESS=consul-server
    ports:
      - "8500:8500"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - consul-client:/bitnami/consul

  nomad-server:
    build: nomad
    depends_on:
      - consul-server
    volumes:
      - ./nomad/server-config:/etc/nomad.d:ro
      - nomad-server:/opt/nomad

volumes:
  consul-server:
    driver: local
  consul-client:
    driver: local
  nomad-server:
    driver: local
